- name: "Establish template"
  hosts: "127.0.0.1"
  vars:
    hostaddr: "server1"
    username: "root"
    servlist: [
      {
        "ansible_host": "192.168.0.114",
        "ansible_port": "2323",
        "ansible_ssh_user": "root",
        "ansible_ssh_pass": "password",
        "ansible_sudo_pass": "password"
      }
    ]
    openpjct_pgdata: "/var/lib/openproject/pgdata"
    openpjct_assets: "/var/lib/openproject/assets"
    openpjct_hostname: "openproject"
    openpjct_port: "9999"
    passhash: "passhash+template"
  tasks:
    - name: "Setting the variables in the playbook template"
      template:
        src: "trap.template.j2"
        dest: "trapplay.yml"
    - name: "Setting the variables in the inventory template"
      template:
        src: "invt.template.j2"
        dest: "register.ini"
